language: go
go:
  - 1.5
sudo: false
install:
  - go get github.com/Sirupsen/logrus
  - go get github.com/streadway/amqp
  - go get golang.org/x/net/context

script:
  - go test
env:
  #example env variable settings
  -travis=true
  -level=debug
  -cpu=10

notifications:
    email: false
    slack:
        rooms:
            - shopgun:UC86BQbSolaCbi1dMJbqZK8j#travis
