language: go
go:
  - 1.5
sudo: false
install:
  - go get github.com/constabulary/gb/...
script:
  - gb build
  - gb test -test.v
env:
  #example env variable settings
  -travis=true
  -level=debug
  -cpu=10
  -AWS_ACCESS_KEY=unset
  -AWS_SECRET_KEY=unset

notifications:
    email: false
    slack:
        rooms:
            - shopgun:UC86BQbSolaCbi1dMJbqZK8j#travis
